// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: video.proto

package videopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestRequest) Reset() {
	*x = ListLatestRequest{}
	mi := &file_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestRequest) ProtoMessage() {}

func (x *ListLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestRequest.ProtoReflect.Descriptor instead.
func (*ListLatestRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *ListLatestRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLatestRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListLatestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestResponse) Reset() {
	*x = ListLatestResponse{}
	mi := &file_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestResponse) ProtoMessage() {}

func (x *ListLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestResponse.ProtoReflect.Descriptor instead.
func (*ListLatestResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{1}
}

func (x *ListLatestResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type ListByAuthorIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorIds     []uint32               `protobuf:"varint,1,rep,packed,name=author_ids,json=authorIds,proto3" json:"author_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByAuthorIDsRequest) Reset() {
	*x = ListByAuthorIDsRequest{}
	mi := &file_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByAuthorIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByAuthorIDsRequest) ProtoMessage() {}

func (x *ListByAuthorIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByAuthorIDsRequest.ProtoReflect.Descriptor instead.
func (*ListByAuthorIDsRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{2}
}

func (x *ListByAuthorIDsRequest) GetAuthorIds() []uint32 {
	if x != nil {
		return x.AuthorIds
	}
	return nil
}

type ListByAuthorIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByAuthorIDsResponse) Reset() {
	*x = ListByAuthorIDsResponse{}
	mi := &file_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByAuthorIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByAuthorIDsResponse) ProtoMessage() {}

func (x *ListByAuthorIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByAuthorIDsResponse.ProtoReflect.Descriptor instead.
func (*ListByAuthorIDsResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{3}
}

func (x *ListByAuthorIDsResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type GetByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDsRequest) Reset() {
	*x = GetByIDsRequest{}
	mi := &file_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDsRequest) ProtoMessage() {}

func (x *GetByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetByIDsRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{4}
}

func (x *GetByIDsRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDsResponse) Reset() {
	*x = GetByIDsResponse{}
	mi := &file_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDsResponse) ProtoMessage() {}

func (x *GetByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetByIDsResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetByIDsResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type ListByPopularityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPopularityRequest) Reset() {
	*x = ListByPopularityRequest{}
	mi := &file_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPopularityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPopularityRequest) ProtoMessage() {}

func (x *ListByPopularityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPopularityRequest.ProtoReflect.Descriptor instead.
func (*ListByPopularityRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{6}
}

func (x *ListByPopularityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListByPopularityRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListByPopularityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoInfo           `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByPopularityResponse) Reset() {
	*x = ListByPopularityResponse{}
	mi := &file_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByPopularityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByPopularityResponse) ProtoMessage() {}

func (x *ListByPopularityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByPopularityResponse.ProtoReflect.Descriptor instead.
func (*ListByPopularityResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{7}
}

func (x *ListByPopularityResponse) GetVideos() []*VideoInfo {
	if x != nil {
		return x.Videos
	}
	return nil
}

type BatchIsLikedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoIds      []uint32               `protobuf:"varint,1,rep,packed,name=video_ids,json=videoIds,proto3" json:"video_ids,omitempty"`
	AccountId     uint32                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsLikedRequest) Reset() {
	*x = BatchIsLikedRequest{}
	mi := &file_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsLikedRequest) ProtoMessage() {}

func (x *BatchIsLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsLikedRequest.ProtoReflect.Descriptor instead.
func (*BatchIsLikedRequest) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{8}
}

func (x *BatchIsLikedRequest) GetVideoIds() []uint32 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

func (x *BatchIsLikedRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type BatchIsLikedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         map[uint32]bool        `protobuf:"bytes,1,rep,name=liked,proto3" json:"liked,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // video_id -> is_liked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchIsLikedResponse) Reset() {
	*x = BatchIsLikedResponse{}
	mi := &file_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchIsLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchIsLikedResponse) ProtoMessage() {}

func (x *BatchIsLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchIsLikedResponse.ProtoReflect.Descriptor instead.
func (*BatchIsLikedResponse) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{9}
}

func (x *BatchIsLikedResponse) GetLiked() map[uint32]bool {
	if x != nil {
		return x.Liked
	}
	return nil
}

type VideoInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId       uint32                 `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PlayUrl        string                 `protobuf:"bytes,6,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,7,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LikesCount     int64                  `protobuf:"varint,9,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	Popularity     int64                  `protobuf:"varint,10,opt,name=popularity,proto3" json:"popularity,omitempty"`
	PlayCount      int64                  `protobuf:"varint,11,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	FavoritesCount int64                  `protobuf:"varint,12,opt,name=favorites_count,json=favoritesCount,proto3" json:"favorites_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideoInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoInfo) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *VideoInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VideoInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoInfo) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *VideoInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *VideoInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoInfo) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *VideoInfo) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *VideoInfo) GetPlayCount() int64 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *VideoInfo) GetFavoritesCount() int64 {
	if x != nil {
		return x.FavoritesCount
	}
	return 0
}

var File_video_proto protoreflect.FileDescriptor

const file_video_proto_rawDesc = "" +
	"\n" +
	"\vvideo.proto\x12\x05video\"A\n" +
	"\x11ListLatestRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\">\n" +
	"\x12ListLatestResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\"7\n" +
	"\x16ListByAuthorIDsRequest\x12\x1d\n" +
	"\n" +
	"author_ids\x18\x01 \x03(\rR\tauthorIds\"C\n" +
	"\x17ListByAuthorIDsResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\"#\n" +
	"\x0fGetByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"<\n" +
	"\x10GetByIDsResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\"G\n" +
	"\x17ListByPopularityRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"D\n" +
	"\x18ListByPopularityResponse\x12(\n" +
	"\x06videos\x18\x01 \x03(\v2\x10.video.VideoInfoR\x06videos\"Q\n" +
	"\x13BatchIsLikedRequest\x12\x1b\n" +
	"\tvideo_ids\x18\x01 \x03(\rR\bvideoIds\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\rR\taccountId\"\x8e\x01\n" +
	"\x14BatchIsLikedResponse\x12<\n" +
	"\x05liked\x18\x01 \x03(\v2&.video.BatchIsLikedResponse.LikedEntryR\x05liked\x1a8\n" +
	"\n" +
	"LikedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xec\x02\n" +
	"\tVideoInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\rR\bauthorId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bplay_url\x18\x06 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\a \x01(\tR\bcoverUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vlikes_count\x18\t \x01(\x03R\n" +
	"likesCount\x12\x1e\n" +
	"\n" +
	"popularity\x18\n" +
	" \x01(\x03R\n" +
	"popularity\x12\x1d\n" +
	"\n" +
	"play_count\x18\v \x01(\x03R\tplayCount\x12'\n" +
	"\x0ffavorites_count\x18\f \x01(\x03R\x0efavoritesCount2\xfe\x02\n" +
	"\fVideoService\x12A\n" +
	"\n" +
	"ListLatest\x12\x18.video.ListLatestRequest\x1a\x19.video.ListLatestResponse\x12P\n" +
	"\x0fListByAuthorIDs\x12\x1d.video.ListByAuthorIDsRequest\x1a\x1e.video.ListByAuthorIDsResponse\x12;\n" +
	"\bGetByIDs\x12\x16.video.GetByIDsRequest\x1a\x17.video.GetByIDsResponse\x12S\n" +
	"\x10ListByPopularity\x12\x1e.video.ListByPopularityRequest\x1a\x1f.video.ListByPopularityResponse\x12G\n" +
	"\fBatchIsLiked\x12\x1a.video.BatchIsLikedRequest\x1a\x1b.video.BatchIsLikedResponseB\x14Z\x12kairos/api/videopbb\x06proto3"

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData []byte
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)))
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_video_proto_goTypes = []any{
	(*ListLatestRequest)(nil),        // 0: video.ListLatestRequest
	(*ListLatestResponse)(nil),       // 1: video.ListLatestResponse
	(*ListByAuthorIDsRequest)(nil),   // 2: video.ListByAuthorIDsRequest
	(*ListByAuthorIDsResponse)(nil),  // 3: video.ListByAuthorIDsResponse
	(*GetByIDsRequest)(nil),          // 4: video.GetByIDsRequest
	(*GetByIDsResponse)(nil),         // 5: video.GetByIDsResponse
	(*ListByPopularityRequest)(nil),  // 6: video.ListByPopularityRequest
	(*ListByPopularityResponse)(nil), // 7: video.ListByPopularityResponse
	(*BatchIsLikedRequest)(nil),      // 8: video.BatchIsLikedRequest
	(*BatchIsLikedResponse)(nil),     // 9: video.BatchIsLikedResponse
	(*VideoInfo)(nil),                // 10: video.VideoInfo
	nil,                              // 11: video.BatchIsLikedResponse.LikedEntry
}
var file_video_proto_depIdxs = []int32{
	10, // 0: video.ListLatestResponse.videos:type_name -> video.VideoInfo
	10, // 1: video.ListByAuthorIDsResponse.videos:type_name -> video.VideoInfo
	10, // 2: video.GetByIDsResponse.videos:type_name -> video.VideoInfo
	10, // 3: video.ListByPopularityResponse.videos:type_name -> video.VideoInfo
	11, // 4: video.BatchIsLikedResponse.liked:type_name -> video.BatchIsLikedResponse.LikedEntry
	0,  // 5: video.VideoService.ListLatest:input_type -> video.ListLatestRequest
	2,  // 6: video.VideoService.ListByAuthorIDs:input_type -> video.ListByAuthorIDsRequest
	4,  // 7: video.VideoService.GetByIDs:input_type -> video.GetByIDsRequest
	6,  // 8: video.VideoService.ListByPopularity:input_type -> video.ListByPopularityRequest
	8,  // 9: video.VideoService.BatchIsLiked:input_type -> video.BatchIsLikedRequest
	1,  // 10: video.VideoService.ListLatest:output_type -> video.ListLatestResponse
	3,  // 11: video.VideoService.ListByAuthorIDs:output_type -> video.ListByAuthorIDsResponse
	5,  // 12: video.VideoService.GetByIDs:output_type -> video.GetByIDsResponse
	7,  // 13: video.VideoService.ListByPopularity:output_type -> video.ListByPopularityResponse
	9,  // 14: video.VideoService.BatchIsLiked:output_type -> video.BatchIsLikedResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_proto_rawDesc), len(file_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
