// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: video.proto

package videopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoService_ListLatest_FullMethodName       = "/video.VideoService/ListLatest"
	VideoService_ListByAuthorIDs_FullMethodName  = "/video.VideoService/ListByAuthorIDs"
	VideoService_GetByIDs_FullMethodName         = "/video.VideoService/GetByIDs"
	VideoService_ListByPopularity_FullMethodName = "/video.VideoService/ListByPopularity"
	VideoService_BatchIsLiked_FullMethodName     = "/video.VideoService/BatchIsLiked"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Video 服务（供 Feed 等下游服务 RPC 调用）
type VideoServiceClient interface {
	// ListLatest 最新视频列表（分页）
	ListLatest(ctx context.Context, in *ListLatestRequest, opts ...grpc.CallOption) (*ListLatestResponse, error)
	// ListByAuthorIDs 按多作者获取视频列表
	ListByAuthorIDs(ctx context.Context, in *ListByAuthorIDsRequest, opts ...grpc.CallOption) (*ListByAuthorIDsResponse, error)
	// GetByIDs 按 ID 列表获取视频
	GetByIDs(ctx context.Context, in *GetByIDsRequest, opts ...grpc.CallOption) (*GetByIDsResponse, error)
	// ListByPopularity 按热度排序视频列表（分页）
	ListByPopularity(ctx context.Context, in *ListByPopularityRequest, opts ...grpc.CallOption) (*ListByPopularityResponse, error)
	// BatchIsLiked 批量查询用户是否已点赞
	BatchIsLiked(ctx context.Context, in *BatchIsLikedRequest, opts ...grpc.CallOption) (*BatchIsLikedResponse, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) ListLatest(ctx context.Context, in *ListLatestRequest, opts ...grpc.CallOption) (*ListLatestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLatestResponse)
	err := c.cc.Invoke(ctx, VideoService_ListLatest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListByAuthorIDs(ctx context.Context, in *ListByAuthorIDsRequest, opts ...grpc.CallOption) (*ListByAuthorIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListByAuthorIDsResponse)
	err := c.cc.Invoke(ctx, VideoService_ListByAuthorIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetByIDs(ctx context.Context, in *GetByIDsRequest, opts ...grpc.CallOption) (*GetByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIDsResponse)
	err := c.cc.Invoke(ctx, VideoService_GetByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListByPopularity(ctx context.Context, in *ListByPopularityRequest, opts ...grpc.CallOption) (*ListByPopularityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListByPopularityResponse)
	err := c.cc.Invoke(ctx, VideoService_ListByPopularity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) BatchIsLiked(ctx context.Context, in *BatchIsLikedRequest, opts ...grpc.CallOption) (*BatchIsLikedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchIsLikedResponse)
	err := c.cc.Invoke(ctx, VideoService_BatchIsLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility.
//
// Video 服务（供 Feed 等下游服务 RPC 调用）
type VideoServiceServer interface {
	// ListLatest 最新视频列表（分页）
	ListLatest(context.Context, *ListLatestRequest) (*ListLatestResponse, error)
	// ListByAuthorIDs 按多作者获取视频列表
	ListByAuthorIDs(context.Context, *ListByAuthorIDsRequest) (*ListByAuthorIDsResponse, error)
	// GetByIDs 按 ID 列表获取视频
	GetByIDs(context.Context, *GetByIDsRequest) (*GetByIDsResponse, error)
	// ListByPopularity 按热度排序视频列表（分页）
	ListByPopularity(context.Context, *ListByPopularityRequest) (*ListByPopularityResponse, error)
	// BatchIsLiked 批量查询用户是否已点赞
	BatchIsLiked(context.Context, *BatchIsLikedRequest) (*BatchIsLikedResponse, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServiceServer struct{}

func (UnimplementedVideoServiceServer) ListLatest(context.Context, *ListLatestRequest) (*ListLatestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLatest not implemented")
}
func (UnimplementedVideoServiceServer) ListByAuthorIDs(context.Context, *ListByAuthorIDsRequest) (*ListByAuthorIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByAuthorIDs not implemented")
}
func (UnimplementedVideoServiceServer) GetByIDs(context.Context, *GetByIDsRequest) (*GetByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByIDs not implemented")
}
func (UnimplementedVideoServiceServer) ListByPopularity(context.Context, *ListByPopularityRequest) (*ListByPopularityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPopularity not implemented")
}
func (UnimplementedVideoServiceServer) BatchIsLiked(context.Context, *BatchIsLikedRequest) (*BatchIsLikedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchIsLiked not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}
func (UnimplementedVideoServiceServer) testEmbeddedByValue()                      {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_ListLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLatestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListLatest(ctx, req.(*ListLatestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListByAuthorIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByAuthorIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListByAuthorIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListByAuthorIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListByAuthorIDs(ctx, req.(*ListByAuthorIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetByIDs(ctx, req.(*GetByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListByPopularity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListByPopularityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListByPopularity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListByPopularity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListByPopularity(ctx, req.(*ListByPopularityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_BatchIsLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIsLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).BatchIsLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_BatchIsLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).BatchIsLiked(ctx, req.(*BatchIsLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLatest",
			Handler:    _VideoService_ListLatest_Handler,
		},
		{
			MethodName: "ListByAuthorIDs",
			Handler:    _VideoService_ListByAuthorIDs_Handler,
		},
		{
			MethodName: "GetByIDs",
			Handler:    _VideoService_GetByIDs_Handler,
		},
		{
			MethodName: "ListByPopularity",
			Handler:    _VideoService_ListByPopularity_Handler,
		},
		{
			MethodName: "BatchIsLiked",
			Handler:    _VideoService_BatchIsLiked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
