// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: social.proto

package socialpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFollowingIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint32                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"` // 关注者（follower）的 account_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingIDsRequest) Reset() {
	*x = GetFollowingIDsRequest{}
	mi := &file_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingIDsRequest) ProtoMessage() {}

func (x *GetFollowingIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingIDsRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingIDsRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowingIDsRequest) GetFollowerId() uint32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

type GetFollowingIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingIds  []uint32               `protobuf:"varint,1,rep,packed,name=following_ids,json=followingIds,proto3" json:"following_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingIDsResponse) Reset() {
	*x = GetFollowingIDsResponse{}
	mi := &file_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingIDsResponse) ProtoMessage() {}

func (x *GetFollowingIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingIDsResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingIDsResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowingIDsResponse) GetFollowingIds() []uint32 {
	if x != nil {
		return x.FollowingIds
	}
	return nil
}

type IsMutualFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserA         uint32                 `protobuf:"varint,1,opt,name=user_a,json=userA,proto3" json:"user_a,omitempty"`
	UserB         uint32                 `protobuf:"varint,2,opt,name=user_b,json=userB,proto3" json:"user_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMutualFollowRequest) Reset() {
	*x = IsMutualFollowRequest{}
	mi := &file_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMutualFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMutualFollowRequest) ProtoMessage() {}

func (x *IsMutualFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMutualFollowRequest.ProtoReflect.Descriptor instead.
func (*IsMutualFollowRequest) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{2}
}

func (x *IsMutualFollowRequest) GetUserA() uint32 {
	if x != nil {
		return x.UserA
	}
	return 0
}

func (x *IsMutualFollowRequest) GetUserB() uint32 {
	if x != nil {
		return x.UserB
	}
	return 0
}

type IsMutualFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutual        bool                   `protobuf:"varint,1,opt,name=mutual,proto3" json:"mutual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMutualFollowResponse) Reset() {
	*x = IsMutualFollowResponse{}
	mi := &file_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMutualFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMutualFollowResponse) ProtoMessage() {}

func (x *IsMutualFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMutualFollowResponse.ProtoReflect.Descriptor instead.
func (*IsMutualFollowResponse) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{3}
}

func (x *IsMutualFollowResponse) GetMutual() bool {
	if x != nil {
		return x.Mutual
	}
	return false
}

var File_social_proto protoreflect.FileDescriptor

const file_social_proto_rawDesc = "" +
	"\n" +
	"\fsocial.proto\x12\x06social\"9\n" +
	"\x16GetFollowingIDsRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\rR\n" +
	"followerId\">\n" +
	"\x17GetFollowingIDsResponse\x12#\n" +
	"\rfollowing_ids\x18\x01 \x03(\rR\ffollowingIds\"E\n" +
	"\x15IsMutualFollowRequest\x12\x15\n" +
	"\x06user_a\x18\x01 \x01(\rR\x05userA\x12\x15\n" +
	"\x06user_b\x18\x02 \x01(\rR\x05userB\"0\n" +
	"\x16IsMutualFollowResponse\x12\x16\n" +
	"\x06mutual\x18\x01 \x01(\bR\x06mutual2\xb4\x01\n" +
	"\rSocialService\x12R\n" +
	"\x0fGetFollowingIDs\x12\x1e.social.GetFollowingIDsRequest\x1a\x1f.social.GetFollowingIDsResponse\x12O\n" +
	"\x0eIsMutualFollow\x12\x1d.social.IsMutualFollowRequest\x1a\x1e.social.IsMutualFollowResponseB\x15Z\x13kairos/api/socialpbb\x06proto3"

var (
	file_social_proto_rawDescOnce sync.Once
	file_social_proto_rawDescData []byte
)

func file_social_proto_rawDescGZIP() []byte {
	file_social_proto_rawDescOnce.Do(func() {
		file_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)))
	})
	return file_social_proto_rawDescData
}

var file_social_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_social_proto_goTypes = []any{
	(*GetFollowingIDsRequest)(nil),  // 0: social.GetFollowingIDsRequest
	(*GetFollowingIDsResponse)(nil), // 1: social.GetFollowingIDsResponse
	(*IsMutualFollowRequest)(nil),   // 2: social.IsMutualFollowRequest
	(*IsMutualFollowResponse)(nil),  // 3: social.IsMutualFollowResponse
}
var file_social_proto_depIdxs = []int32{
	0, // 0: social.SocialService.GetFollowingIDs:input_type -> social.GetFollowingIDsRequest
	2, // 1: social.SocialService.IsMutualFollow:input_type -> social.IsMutualFollowRequest
	1, // 2: social.SocialService.GetFollowingIDs:output_type -> social.GetFollowingIDsResponse
	3, // 3: social.SocialService.IsMutualFollow:output_type -> social.IsMutualFollowResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_social_proto_init() }
func file_social_proto_init() {
	if File_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_social_proto_goTypes,
		DependencyIndexes: file_social_proto_depIdxs,
		MessageInfos:      file_social_proto_msgTypes,
	}.Build()
	File_social_proto = out.File
	file_social_proto_goTypes = nil
	file_social_proto_depIdxs = nil
}
