// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: social.proto

package socialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_GetFollowingIDs_FullMethodName = "/social.SocialService/GetFollowingIDs"
	SocialService_IsMutualFollow_FullMethodName  = "/social.SocialService/IsMutualFollow"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Social 服务（供 Feed、IM 等下游服务 RPC 调用）
type SocialServiceClient interface {
	// GetFollowingIDs 获取某用户关注的用户 ID 列表
	GetFollowingIDs(ctx context.Context, in *GetFollowingIDsRequest, opts ...grpc.CallOption) (*GetFollowingIDsResponse, error)
	// IsMutualFollow 是否互相关注（供 IM 校验私聊权限）
	IsMutualFollow(ctx context.Context, in *IsMutualFollowRequest, opts ...grpc.CallOption) (*IsMutualFollowResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) GetFollowingIDs(ctx context.Context, in *GetFollowingIDsRequest, opts ...grpc.CallOption) (*GetFollowingIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingIDsResponse)
	err := c.cc.Invoke(ctx, SocialService_GetFollowingIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) IsMutualFollow(ctx context.Context, in *IsMutualFollowRequest, opts ...grpc.CallOption) (*IsMutualFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsMutualFollowResponse)
	err := c.cc.Invoke(ctx, SocialService_IsMutualFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
//
// Social 服务（供 Feed、IM 等下游服务 RPC 调用）
type SocialServiceServer interface {
	// GetFollowingIDs 获取某用户关注的用户 ID 列表
	GetFollowingIDs(context.Context, *GetFollowingIDsRequest) (*GetFollowingIDsResponse, error)
	// IsMutualFollow 是否互相关注（供 IM 校验私聊权限）
	IsMutualFollow(context.Context, *IsMutualFollowRequest) (*IsMutualFollowResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) GetFollowingIDs(context.Context, *GetFollowingIDsRequest) (*GetFollowingIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFollowingIDs not implemented")
}
func (UnimplementedSocialServiceServer) IsMutualFollow(context.Context, *IsMutualFollowRequest) (*IsMutualFollowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsMutualFollow not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call panics, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_GetFollowingIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetFollowingIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetFollowingIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetFollowingIDs(ctx, req.(*GetFollowingIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_IsMutualFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsMutualFollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).IsMutualFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_IsMutualFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).IsMutualFollow(ctx, req.(*IsMutualFollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowingIDs",
			Handler:    _SocialService_GetFollowingIDs_Handler,
		},
		{
			MethodName: "IsMutualFollow",
			Handler:    _SocialService_IsMutualFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
